name: wt-js
scripts:
  minify: gulp
  fmt: cd ../.. && dprint fmt
  checkfmt: cd ../.. && dprint check
author: Emweb bv
license : GPL-2.0-only
private: true
devDependencies:
  dprint: ^0.32.1
  gulp: ^4.0.2
  gulp-rename: ^2.0.0
  gulp-terser: ^2.1.0
